# Generated by Django 2.1.5 on 2019-02-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
