# Generated by Django 2.1.5 on 2019-02-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_name', models.CharField(max_length=50)),
                ('contacts_photo', models.ImageField(upload_to='contacts_images')),
                ('contacts_text', models.TextField()),
            ],
        ),
    ]
