# Generated by Django 2.2.7 on 2019-11-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fasaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasaq_title', models.CharField(max_length=50)),
                ('fasaq_describe', models.TextField()),
            ],
        ),
    ]
